logging:
  file: logs/m122.log
api:
  nba:
    url: https://api-nba-v1.p.rapidapi.com/players/statistics
    key: 123
    properties:
	season: 2020
	id: 236
  football:
    url: https://api-football-v1.p.rapidapi.com/v3/players/topscorers
    properties:
      league: 39
      season: 2020
    key: 123
smtp:
  host: smtp.gmail.com
  user: test
  password: test
ftp:
  host: floriangubler.bplaced.net
