logging:
  file: logs/m122.log
api:
  nba:
    url: https://basketball-data.p.rapidapi.com/tournament/leaderboard/point
    properties:
        tournamentId: 1
  football:
    url: https://api-football-v1.p.rapidapi.com/v3/players/topscorers
    properties:
      league: 39
      season: 2020
smtp:
  host: smtp.gmail.com
  user: test
  password: test
ftp:
  host: floriangubler.bplaced.net
