logging:
  file: logs/m122.log
api:
  nba:
    url: https://basketball-data.p.rapidapi.com/tournament/leaderboard/point
    properties:
      tournamentId: 1
  football:
    url: https://api-football-v1.p.rapidapi.com/v3/players/topscorers
    properties:
      league: 2
smtp:
  host: smtp.gmail.com
  port: 465
  mail: 
    from: m122.testmail@gmail.com
    to: gubler.florian@gmx.net,romer.laurent@gmail.com
    subject: New Sport Report (M122)
    template: templates/mail.html
ftp:
  host: floriangubler.bplaced.net
  user: floriangubler
  uploadDir: "/m122/"
pdf:
  template: templates/report.html
  tmpfile: tmp/report.pdf
