logging:
  file: logs/m122.log
api:
  nba:
    url: https://api-nba-v1.p.rapidapi.com/players/statistics
    host: api-nba-v1.p.rapidapi.com
  football:
    url: https://api-football-v1.p.rapidapi.com/v3/players/topscorers
    host: api-football-v1.p.rapidapi.com
    properties:
      league: 2
smtp:
  host: smtp.gmail.com
  user: test
  password: test
ftp:
  host: floriangubler.bplaced.net
pdf:
  template: templates/report.html
  tmpfile: tmp/report.pdf
